[package]
name = "task_manager"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.26.0"
crossterm = "0.27.0"
rusqlite = { version = "0.31.0", features = ["bundled"] }
fuzzy-matcher = "0.3.7"
